[env]
PATH = "/Users/bytedance/.cargo/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

[alias]
build-linux-arm64 = "zigbuild --release --target aarch64-unknown-linux-gnu"
build-linux-arm64-musl = "zigbuild --release --target aarch64-unknown-linux-musl"
